[DEFAULT]
DIR_ROOT_RUNS = runs
DIR_RHO_TARGET = simulaciones/rho_target
DIR_RHO_ESTIMADO = simulaciones/tomography/rho_estimado/tomografia_barrido
DIR_RHO_ESTIMADO_TEST = simulaciones/tomography/rho_estimado/tomografia_test
DIR_TOM_FIDELIDAD = simulaciones/tomography/fidelidad
DIR_GRAFICOS_DENSITYMATRICES = graficos/density_matrices
DIR_GRAFICOS_TOM = graficos/tomography/tomografia_barrido
DIR_GRAFICOS_TOM_TEST = graficos/tomography/tomografia_test
DIR_MEASUREMENTS = simulaciones/measurements

[user_run]
dir_user_run = test_5q_con_beta-01
dir_user_estados = Estados_random
nqubits = 5
nombre_tipo_tomografia = Completa
nombre_base_observables = sic_povm
descripcion_estados = Random rango 1 
rango = 1
vqt = false
vqt_inf = false
vqt_hib = true
maxent = false
maxent_exp = false

[parametros_opt]
alpha = 1.0
#beta = 0.01
#beta = 0.003
#beta = 1.0
beta = 0.1
max_iter_vqt = 300000
max_iter_vqt_inf = 300000
max_iter_vqt_hib = 300000
max_iter_maxent = 100000
max_iter_maxent_exp = 300000
stop_loss_maxent_exp = 1e-6

[tomografia_barrido]
realizar = true
min_cant_obs = 1
max_cant_obs = 10
max_cant_estados = 3
save_intermediate_states = true
desde_estado_index = 2

[tomografia_test]
realizar = false
cant_obs = 20
cant_estados = 10
desde_estado_index = 1

[mediciones]
generar = true
;ruta_pickle_lista_mediciones_por_estados_custom =
ruido = false
tipo_ruido =  uniforme

[graficar]
graficar_barrido = true
